# Generated by Django 3.1 on 2020-08-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacatcher', '0002_record_run_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='time',
        ),
        migrations.AddField(
            model_name='record',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
