# Generated by Django 3.1 on 2020-08-28 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('start_time', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(default='no comments')),
                ('start_balance', models.FloatField(default=200.0)),
                ('duration', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd_balance', models.FloatField()),
                ('btc_balance', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tester.run')),
            ],
        ),
    ]
