# Generated by Django 3.1 on 2020-08-28 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0002_auto_20200829_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
