# Generated by Django 3.1 on 2020-08-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0003_auto_20200829_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snapshot',
            name='btc_balance',
        ),
        migrations.AddField(
            model_name='run',
            name='last_action',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='run',
            name='last_balances',
            field=models.TextField(default="{'usdt': 200.}"),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='balances',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='usd_balance',
            field=models.FloatField(null=True),
        ),
    ]
