# Generated by Django 3.1 on 2020-08-30 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datacatcher', '0003_auto_20200830_1744'),
        ('tester', '0005_auto_20200830_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='last_action',
        ),
        migrations.RemoveField(
            model_name='run',
            name='last_balances',
        ),
        migrations.AddField(
            model_name='snapshot',
            name='record',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='datacatcher.record'),
        ),
    ]
