# Generated by Django 3.1 on 2020-08-30 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datacatcher', '0003_auto_20200830_1744'),
        ('tester', '0006_auto_20200830_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datacatcher.record'),
        ),
    ]
