# Generated by Django 3.1 on 2020-08-31 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0007_auto_20200830_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('delta', models.TextField()),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tester.snapshot')),
            ],
        ),
    ]
