# Generated by Django 3.1 on 2020-08-31 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0008_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='end_balances',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='end_usdt',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='duration',
            field=models.DurationField(null=True),
        ),
    ]
